import React from 'react';
import {SafeAreaView,View,Text,Pressable,StyleSheet,ScrollView} from 'react-native';
import {useRouter} from 'expo-router';
import {StatusBar} from 'expo-status-bar';

const sections=[
 ['⚡','Actualités','Toute l’actualité du football marocain','/web?path=/fil-actualite'],
 ['🇲🇦','Mon XI','Compose ton équipe des Lions de l’Atlas','/web?path=/mon-xi'],
 ['☕','Café des Lions','Discute avec la communauté AtlasFoot','/web?path=/cafe'],
 ['🎥','Vidéos','Retrouve les vidéos AtlasFoot','/web?path=/videos']
];
export default function Home(){const r=useRouter();return <SafeAreaView style={s.safe}><StatusBar style="light"/><ScrollView contentContainerStyle={s.page}><View style={s.head}><Text style={s.brand}>ATLAS<Text style={s.red}>FOOT</Text></Text><Text style={s.tag}>100% FOOTBALL MAROCAIN</Text></View><View style={s.hero}><Text style={s.kicker}>🇲🇦 L’APPLICATION DES SUPPORTERS</Text><Text style={s.title}>TOUT LE FOOT MAROCAIN, DANS TA POCHE.</Text><Text style={s.copy}>Lions de l’Atlas, mercato, joueurs marocains, Mon XI et Café des Lions.</Text><Pressable style={s.primary} onPress={()=>r.push('/web?path=/fil-actualite')}><Text style={s.primaryText}>Voir les dernières actualités →</Text></Pressable></View><Text style={s.section}>Explorer AtlasFoot</Text>{sections.map(([icon,title,desc,path])=><Pressable key={title} style={s.card} onPress={()=>r.push(path)}><Text style={s.icon}>{icon}</Text><View style={{flex:1}}><Text style={s.cardTitle}>{title}</Text><Text style={s.cardText}>{desc}</Text></View><Text style={s.arrow}>›</Text></Pressable>)}<Text style={s.foot}>ATLASFOOT.FR · LA COMMUNAUTÉ DU FOOT MAROCAIN</Text></ScrollView></SafeAreaView>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:'#07140f'},page:{padding:20,paddingBottom:40},head:{paddingTop:12,paddingBottom:25},brand:{fontSize:28,fontWeight:'900',color:'#fff',letterSpacing:-1},red:{color:'#e32929'},tag:{fontSize:10,color:'#91a59a',fontWeight:'800',letterSpacing:2,marginTop:3},hero:{backgroundColor:'#10231a',borderRadius:24,padding:24,borderWidth:1,borderColor:'#234031'},kicker:{color:'#d5a82b',fontSize:11,fontWeight:'900',letterSpacing:1},title:{color:'#fff',fontSize:34,fontWeight:'900',lineHeight:36,marginTop:12},copy:{color:'#b7c5bd',fontSize:16,lineHeight:23,marginTop:12},primary:{backgroundColor:'#d92727',padding:16,borderRadius:14,marginTop:22},primaryText:{color:'#fff',fontWeight:'900',textAlign:'center'},section:{color:'#fff',fontWeight:'900',fontSize:20,marginTop:30,marginBottom:12},card:{flexDirection:'row',alignItems:'center',gap:14,backgroundColor:'#0d1d16',padding:18,borderRadius:18,marginBottom:11,borderWidth:1,borderColor:'#1b3327'},icon:{fontSize:25},cardTitle:{color:'#fff',fontSize:17,fontWeight:'900'},cardText:{color:'#91a59a',fontSize:13,marginTop:3},arrow:{color:'#fff',fontSize:28},foot:{textAlign:'center',color:'#53675c',fontSize:10,fontWeight:'800',letterSpacing:1,marginTop:22}});