'use client'
import Link from 'next/link'
import {useEffect,useState} from 'react'
import {createClient} from '@supabase/supabase-js'
const supabase=createClient(process.env.NEXT_PUBLIC_SUPABASE_URL||'https://czwiqkbojqqdatqohnrs.supabase.co',process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY||'sb_publishable_9H0YCCeSFQ-KgWucLDQ__w_au0A3nqP')
export default function Moderation(){
 const [me,setMe]=useState(null),[members,setMembers]=useState([]),[reports,setReports]=useState([]),[msg,setMsg]=useState('')
 useEffect(()=>{init()},[])
 async function init(){const {data:{user}}=await supabase.auth.getUser();if(!user)return setMsg('Connecte-toi avec le compte administrateur.');const {data:p}=await supabase.from('profiles').select('id,is_admin').eq('id',user.id).single();if(!p?.is_admin)return setMsg('Accès réservé à l’administrateur.');setMe(user);load()}
 async function load(){const {data:m}=await supabase.from('profiles').select('id,username,moderation_status,suspended_until,moderation_reason,is_admin').order('username');setMembers(m||[]);const {data:r}=await supabase.from('cafe_reports').select('id,post_id,reason,details,created_at,reporter_id').order('created_at',{ascending:false}).limit(100);setReports(r||[])}
 async function moderate(id,action){const reason=window.prompt('Motif de la modération (optionnel) :')||'';const {error}=await supabase.rpc('admin_moderate_member',{target_user:id,action_name:action,reason_text:reason});if(error)return alert(error.message);await load()}
 async function hidePost(postId){if(!confirm('Masquer cette publication ?'))return;const {error}=await supabase.from('cafe_posts').update({is_hidden:true}).eq('id',postId);if(error)alert(error.message);else load()}
 if(!me)return <main className="wrap" style={{padding:'50px 0'}}><Link href="/" className="brand">ATLAS<b>FOOT</b></Link><div className="card" style={{marginTop:20}}>{msg||'Vérification du compte…'}</div></main>
 return <><header className="top"><div className="wrap nav"><Link className="brand" href="/">ATLAS<b>FOOT</b></Link><div style={{display:'flex',gap:8,flexWrap:'wrap'}}><Link className="btn dark" href="/admin/utilisateurs">👥 Utilisateurs</Link><Link className="btn dark" href="/cafe">← Café des Lions</Link></div></div></header><main className="wrap" style={{padding:'32px 0'}}><span className="eyebrow">🛡️ ADMINISTRATION</span><h1>Modération du Café</h1><div className="card"><h2>Membres</h2>{members.map(x=><div key={x.id} style={{padding:'14px 0',borderBottom:'1px solid #26382f'}}><b>{x.username||'Supporter'}</b> {x.is_admin&&<span className="eyebrow">ADMIN</span>}<div className="meta">Statut : {x.moderation_status}{x.suspended_until?' · jusqu’au '+new Date(x.suspended_until).toLocaleString('fr-FR'):''}</div>{!x.is_admin&&<div style={{display:'flex',gap:8,flexWrap:'wrap',marginTop:8}}><button className="btn dark" onClick={()=>moderate(x.id,'active')}>Réactiver</button><button className="btn dark" onClick={()=>moderate(x.id,'24h')}>Suspendre 24 h</button><button className="btn dark" onClick={()=>moderate(x.id,'7d')}>Suspendre 7 jours</button><button className="btn red" onClick={()=>moderate(x.id,'ban')}>Bannir</button></div>}</div>)}</div><div className="card" style={{marginTop:20}}><h2>Signalements</h2>{reports.length===0?<p className="meta">Aucun signalement.</p>:reports.map(r=><div key={r.id} style={{padding:'14px 0',borderBottom:'1px solid #26382f'}}><b>{r.reason||'Signalement'}</b><p>{r.details}</p><div className="meta">{new Date(r.created_at).toLocaleString('fr-FR')}</div><button className="btn red" onClick={()=>hidePost(r.post_id)}>Masquer la publication</button></div>)}</div></main></>}
