import Link from 'next/link'
import HomeLiveFeed from './components/HomeLiveFeed'
import YouTubeVideoFeed from './components/YouTubeVideoFeed'
import EngagementHub from './components/EngagementHub'
const players=[['Bounou','GK',50,88],['Hakimi','DD',84,72],['Aguerd','DC',62,72],['Chadi Riad','DC',38,72],['Mazraoui','DG',16,72],['Amrabat','MDC',50,51],['Ounahi','MC',32,42],['El Khannouss','MC',68,42],['Brahim Díaz','AD',80,22],['El Kaabi','BU',50,16],['Ezzalzouli','AG',20,22]]
export default function Home(){return <><header className="top"><div className="wrap nav"><Link className="brand" href="/">ATLAS<b>FOOT</b></Link><nav className="navlinks"><a href="#actus">Actualités</a><Link href="/fil-actualite">⚡ Actualité en direct</Link><Link href="/videos">🎥 Vidéos</Link><Link href="/mon-xi">Mon XI</Link><Link href="/cafe">☕ Café</Link></nav><Link className="btn red" href="/cafe">Rejoindre</Link></div></header>
<section className="breaking"><div className="wrap"><b>🔴 ACTUALITÉ EN DIRECT</b><span>Actualités du football marocain</span><Link href="/fil-actualite">Suivre le direct →</Link></div></section>
<section className="hero"><div className="wrap"><span className="eyebrow">🇲🇦 LA MAISON DU FOOTBALL MAROCAIN</span><h1>Toute l’actualité du <em>football marocain</em> est ici.</h1><p>Lions de l’Atlas, Botola, Marocains du monde, mercato, jeunes talents et la voix des supporters réunis au même endroit.</p><div className="heroActions"><Link className="btn red" href="/fil-actualite">⚡ Actualité en direct</Link><Link className="btn dark" href="/mon-xi">🦁 Composer mon XI</Link></div></div></section>
<main className="wrap homeWithRail"><div className="homeMainColumn"><EngagementHub/>
<section id="actus"><div className="sectionTitle"><h2>À la une</h2><Link className="btn dark" href="/fil-actualite">Toutes les infos →</Link></div><div className="cards"><Link className="card headlineCard" href="/fil-actualite?cat=Lions%20de%20l%E2%80%99Atlas"><span className="eyebrow">LIONS DE L’ATLAS</span><h3>La sélection en continu</h3><p>Matchs, préparation, déclarations et dernières informations.</p><span className="cardCta">Voir les dernières infos →</span></Link><Link className="card headlineCard" href="/fil-actualite?cat=Marocains%20du%20monde"><span className="eyebrow">MAROCAINS DU MONDE</span><h3>Nos joueurs à l’étranger</h3><p>Performances, transferts et actualités des internationaux.</p><span className="cardCta">Suivre les joueurs →</span></Link><Link className="card headlineCard" href="/fil-actualite?cat=Botola%20Pro"><span className="eyebrow">BOTOLA PRO</span><h3>Le championnat marocain</h3><p>Résultats, mercato et actualités des clubs du Royaume.</p><span className="cardCta">Voir la Botola →</span></Link></div></section>
<section className="homeVideos"><div className="sectionTitle"><div><span className="eyebrow">🎥 ATLASFOOT TV</span><h2>Dernières vidéos</h2></div><Link className="btn dark" href="/videos">Vidéos & interviews →</Link></div><YouTubeVideoFeed limit={4}/></section>
<section id="xi"><div className="sectionTitle"><div><span className="eyebrow">🦁 LE CHOIX DES SUPPORTERS</span><h2>XI du Maroc</h2></div><Link className="btn red" href="/mon-xi">Composer mon XI</Link></div><div className="pitch">{players.map((p,i)=><div className="player" key={p[0]} style={{left:p[2]+'%',top:p[3]+'%'}}><div className="shirt">{i+1}</div><div className="playerName">{p[0]}</div><div className="pct">Position {p[1]}</div></div>)}</div></section>
<section className="returnZone"><div className="card"><span className="eyebrow">🌍 MAROCAINS DU MONDE</span><h2>Qui a brillé aujourd’hui ?</h2><p>Retrouve les performances et dernières nouvelles des Lions dans leurs clubs.</p><Link className="btn dark" href="/fil-actualite?cat=Marocains%20du%20monde">Voir les performances →</Link></div><div className="card"><span className="eyebrow">☕ COMMUNAUTÉ</span><h2>Le Café des Lions</h2><p>Publie, commente, aime, vote et échange avec les supporters.</p><Link className="btn red" href="/cafe">Entrer dans le Café →</Link></div></section></div><HomeLiveFeed/></main><footer className="footer"><div className="wrap">AtlasFoot · La communauté du football marocain</div></footer></>}
