'use client'
import Link from 'next/link'
import {useEffect,useMemo,useState} from 'react'
import {createClient} from '@supabase/supabase-js'

const supabase=createClient(process.env.NEXT_PUBLIC_SUPABASE_URL||'https://czwiqkbojqqdatqohnrs.supabase.co',process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY||'sb_publishable_9H0YCCeSFQ-KgWucLDQ__w_au0A3nqP')
const rooms=[['all','🔥 Pour vous'],['lions','🇲🇦 Lions de l’Atlas'],['botola','🏆 Botola Pro'],['marocains_monde','🌍 Marocains du monde'],['mercato','🔁 Mercato'],['jeunes','🌟 Jeunes talents'],['mondial','🌎 Mondial'],['discussion','☕ Discussion libre']]

export default function Cafe(){
 const [room,setRoom]=useState('all'),[text,setText]=useState(''),[posts,setPosts]=useState([]),[user,setUser]=useState(null),[isAdmin,setIsAdmin]=useState(false),[auth,setAuth]=useState(false),[signup,setSignup]=useState(false),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[pseudo,setPseudo]=useState(''),[toast,setToast]=useState(''),[poll,setPoll]=useState(false),[question,setQuestion]=useState(''),[options,setOptions]=useState(''),[comments,setComments]=useState({}),[selectedVotes,setSelectedVotes]=useState({})
 const say=t=>{setToast(t);setTimeout(()=>setToast(''),4800)}
 const activeRoom=useMemo(()=>rooms.find(r=>r[0]===room)?.[1]||'Pour vous',[room])
 async function syncUser(u){setUser(u||null);if(!u){setIsAdmin(false);return}const {data:p}=await supabase.from('profiles').select('is_admin').eq('id',u.id).single();setIsAdmin(!!p?.is_admin)}
 useEffect(()=>{supabase.auth.getUser().then(({data})=>syncUser(data.user||null));const {data:{subscription}}=supabase.auth.onAuthStateChange((_e,s)=>syncUser(s?.user||null));load();const ch=supabase.channel('cafe-live').on('postgres_changes',{event:'*',schema:'public',table:'cafe_posts'},load).on('postgres_changes',{event:'*',schema:'public',table:'cafe_comments'},load).on('postgres_changes',{event:'*',schema:'public',table:'cafe_post_likes'},load).on('postgres_changes',{event:'*',schema:'public',table:'cafe_poll_votes'},load).subscribe();return()=>{subscription.unsubscribe();supabase.removeChannel(ch)}},[])
 async function load(){let q=supabase.from('cafe_posts').select('id,author_id,room,post_type,content,poll_question,poll_options,created_at,profiles(username),cafe_post_likes(user_id),cafe_comments(id,content,created_at,author_id,profiles(username)),cafe_poll_votes(user_id,option_index)').eq('is_hidden',false).order('created_at',{ascending:false}).limit(50);const {data,error}=await q;if(!error)setPosts(data||[])}
 async function requireUser(){const {data}=await supabase.auth.getUser();if(!data.user){setSignup(false);setAuth(true);say('Connecte-toi pour participer au Café des Lions.');return null}return data.user}
 async function publish(){
  const u=await requireUser();if(!u)return
  const body=text.trim(),pollQuestion=question.trim()
  if(!poll&&!body)return say('Écris un message avant de publier.')
  if(poll){
   const opts=options.split(',').map(x=>x.trim()).filter(Boolean)
   if(!pollQuestion&&!body)return say('Ajoute une question au sondage.')
   if(opts.length<2)return say('Ajoute au moins deux choix séparés par des virgules.')
   const finalQuestion=pollQuestion||body
   const payload={author_id:u.id,room:room==='all'?'lions':room,post_type:'poll',content:body||finalQuestion,poll_question:finalQuestion,poll_options:opts}
   const {error}=await supabase.from('cafe_posts').insert(payload)
   if(error)return say('Publication impossible : '+error.message)
  }else{
   const {error}=await supabase.from('cafe_posts').insert({author_id:u.id,room:room==='all'?'lions':room,post_type:'text',content:body})
   if(error)return say('Publication impossible : '+error.message)
  }
  setText('');setQuestion('');setOptions('');setPoll(false);say('✅ Publication envoyée dans le Café des Lions.');load()
 }
 async function like(post){const u=await requireUser();if(!u)return;const liked=post.cafe_post_likes?.some(x=>x.user_id===u.id);const q=supabase.from('cafe_post_likes');const {error}=liked?await q.delete().eq('post_id',post.id).eq('user_id',u.id):await q.insert({post_id:post.id,user_id:u.id});if(!error)load()}
 async function comment(postId){const u=await requireUser(),content=(comments[postId]||'').trim();if(!u||!content)return;const {error}=await supabase.from('cafe_comments').insert({post_id:postId,author_id:u.id,content});if(error)return say('Commentaire impossible.');setComments({...comments,[postId]:''});say('Commentaire envoyé.');load()}
 async function vote(postId,index){if(index===undefined||index===null)return say('Choisis une réponse avant d’envoyer ton vote.');const u=await requireUser();if(!u)return;const {error}=await supabase.from('cafe_poll_votes').upsert({post_id:postId,user_id:u.id,option_index:index},{onConflict:'post_id,user_id'});if(error)return say('Vote impossible : '+error.message);say('✅ Ton vote a été enregistré.');load()}
 async function report(postId){const u=await requireUser();if(!u)return;const {error}=await supabase.from('cafe_reports').insert({reporter_id:u.id,post_id:postId,reason:'autre',details:'Signalement depuis le Café des Lions'});say(error?'Signalement impossible.':'Merci. Le contenu a été transmis à la modération.')}
 async function submitAuth(){if(!email||password.length<6)return say('Utilise un e-mail valide et un mot de passe de 6 caractères minimum.');if(signup){const {error}=await supabase.auth.signUp({email,password,options:{data:{username:pseudo||email.split('@')[0],pseudo:pseudo||email.split('@')[0]},emailRedirectTo:window.location.origin+'/cafe'}});if(error)return say('Inscription impossible : '+error.message);setAuth(false);say('✅ Compte créé avec succès. Vérifiez votre e-mail pour activer votre compte.')}else{const {error}=await supabase.auth.signInWithPassword({email,password});if(error)return say('Connexion impossible : vérifie tes identifiants et la validation de ton e-mail.');setAuth(false);say('Bienvenue dans le Café des Lions !')}}
 const visible=room==='all'?posts:posts.filter(p=>p.room===room)
 return <><header className="top"><div className="wrap nav"><Link className="brand" href="/">ATLAS<b>FOOT</b></Link><nav className="navlinks"><Link href="/">Actualités</Link><Link href="/mon-xi">Mon XI</Link><Link className="active" href="/cafe">☕ Café des Lions</Link>{isAdmin&&<Link href="/admin/moderation">🛡️ Admin</Link>}</nav>{user?<button className="btn dark" onClick={async()=>{await supabase.auth.signOut();setIsAdmin(false);say('Déconnecté.')}}>Déconnexion</button>:<><button className="btn dark" onClick={()=>{setSignup(false);setAuth(true)}}>Se connecter</button><button className="btn red" onClick={()=>{setSignup(true);setAuth(true)}}>S’inscrire</button></>}</div></header>
<section className="hero cafeHero"><div className="wrap"><span className="eyebrow">☕ 100% SUPPORTERS</span><h1>LE CAFÉ <em>DES LIONS</em></h1><p>Débats, sondages, mercato et passion du football marocain. Ici, la parole est aux supporters.</p></div></section>
<div className="wrap layout"><aside className="card side"><h4>Salons</h4>{rooms.map(([id,label])=><button key={id} className={'room '+(room===id?'active':'')} onClick={()=>setRoom(id)}>{label}</button>)}</aside>
<main><div className="card compose"><div className="composeTitle"><b>Publier dans {activeRoom}</b><span className="meta">{user?'Compte connecté':'Connexion requise pour publier'}</span></div><textarea value={text} onChange={e=>setText(e.target.value)} placeholder={poll?'Texte facultatif pour accompagner le sondage':'Quoi de neuf chez les Lions ?'}/><div className="composeFoot"><button className="btn dark" onClick={()=>setPoll(!poll)}>📊 {poll?'Retirer le sondage':'Ajouter un sondage'}</button><button className="btn red" onClick={publish}>Publier</button></div>{poll&&<div className="pollEditor"><input value={question} onChange={e=>setQuestion(e.target.value)} placeholder="Question du sondage"/><input value={options} onChange={e=>setOptions(e.target.value)} placeholder="Choix séparés par des virgules"/></div>}</div>
{visible.length===0&&<div className="card empty">Aucune discussion pour le moment. Lance le premier débat !</div>}
{visible.map(p=>{const author=p.profiles?.username||'Supporter';const liked=!!user&&p.cafe_post_likes?.some(x=>x.user_id===user.id);const votes=p.cafe_poll_votes||[];const savedVote=user?votes.find(v=>v.user_id===user.id)?.option_index:undefined;const selected=selectedVotes[p.id]??savedVote;return <article className="card post" key={p.id}><div className="postHead"><div className="avatar">{author[0]?.toUpperCase()}</div><div><b>{author}</b><div className="meta">{new Date(p.created_at).toLocaleDateString('fr-FR')} · Supporter AtlasFoot</div></div><span className="tag">{rooms.find(r=>r[0]===p.room)?.[1]||p.room}</span></div><p className="postText">{p.content}</p>{p.post_type==='poll'&&Array.isArray(p.poll_options)&&<div className="postPoll"><b>{p.poll_question}</b>{p.poll_options.map((o,i)=>{const n=votes.filter(v=>v.option_index===i).length,pc=votes.length?Math.round(n*100/votes.length):0;return <button className={'poll '+(selected===i?'active':'')} key={o} onClick={()=>setSelectedVotes({...selectedVotes,[p.id]:i})}><span>{selected===i?'✓ ':''}{o}</span><strong>{pc}%</strong></button>})}<button className="btn red full" onClick={()=>vote(p.id,selected)}>{savedVote===undefined?'Envoyer mon vote':'Modifier mon vote'}</button><small>{votes.length} vote{votes.length>1?'s':''} · résultats en direct</small></div>}<div className="actions"><button onClick={()=>like(p)}>{liked?'❤️':'🤍'} {p.cafe_post_likes?.length||0}</button><button>💬 {p.cafe_comments?.length||0}</button><button onClick={()=>report(p.id)}>🚩 Signaler</button></div>{p.cafe_comments?.slice(0,5).map(c=><div className="comment" key={c.id}><b>{c.profiles?.username||'Supporter'}</b> {c.content}</div>)}<div className="commentBox"><input value={comments[p.id]||''} onChange={e=>setComments({...comments,[p.id]:e.target.value})} placeholder="Répondre à cette discussion…"/><button className="btn dark" onClick={()=>comment(p.id)}>Envoyer le commentaire</button></div></article>})}</main>
<aside className="right"><div className="card"><span className="eyebrow">DÉBAT DU JOUR</span><h3>Qui doit être incontournable dans le prochain XI ?</h3><p>Participe aux discussions et compare ton équipe avec le choix de la communauté.</p><Link className="btn red" href="/mon-xi">Composer mon XI</Link></div><div className="card"><h3>🔥 Tendances</h3><p>#LionsDeLAtlas</p><p>#MercatoMaroc</p><p>#BotolaPro</p></div><div className="card"><h3>🛡️ Modération</h3><p>Les contenus signalés sont enregistrés pour traitement par l’administrateur.</p>{isAdmin&&<Link className="btn dark" href="/admin/moderation">Ouvrir la modération →</Link>}</div></aside></div>
{auth&&<div className="modal"><div className="modalBox"><h2>{signup?'Créer mon compte':'Connexion'}</h2>{signup&&<input value={pseudo} onChange={e=>setPseudo(e.target.value)} placeholder="Pseudo"/>}<input value={email} onChange={e=>setEmail(e.target.value)} type="email" placeholder="E-mail"/><input value={password} onChange={e=>setPassword(e.target.value)} type="password" placeholder="Mot de passe (6 caractères minimum)"/><button className="btn red full" onClick={submitAuth}>{signup?'Créer mon compte':'Se connecter'}</button><button className="btn dark full" onClick={()=>setAuth(false)}>Fermer</button></div></div>}{toast&&<div className="toast">{toast}</div>}</>}
