'use client'
import Link from 'next/link'
import {useEffect,useState} from 'react'
import {createClient} from '@supabase/supabase-js'

const url=process.env.NEXT_PUBLIC_SUPABASE_URL
const key=process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY
const supabase=url&&key?createClient(url,key):null
const rooms=['🔥 Pour vous','🇲🇦 Lions de l’Atlas','🏆 Botola Pro','🌍 Marocains du monde','🔁 Mercato','🌟 Jeunes talents','🌎 Mondial','☕ Discussion libre']
const demo=[{id:'d1',author:'YoussefCasa',room:'Lions de l’Atlas',body:'Quel milieu aimeriez-vous voir titulaire au prochain match ? J’aimerais voir davantage les jeunes prendre leur chance.',likes:18},{id:'d2',author:'RifFoot',room:'Mercato',body:'Suivons de près les mouvements de nos internationaux cet été. Plusieurs dossiers peuvent changer la hiérarchie chez les Lions.',likes:11}]
export default function Cafe(){
 const [room,setRoom]=useState(rooms[0]),[text,setText]=useState(''),[posts,setPosts]=useState(demo),[auth,setAuth]=useState(null),[signup,setSignup]=useState(false),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[pseudo,setPseudo]=useState(''),[toast,setToast]=useState('')
 const say=t=>{setToast(t);setTimeout(()=>setToast(''),4500)}
 useEffect(()=>{if(!supabase)return;load();const ch=supabase.channel('cafe-live').on('postgres_changes',{event:'*',schema:'public',table:'cafe_posts'},load).subscribe();return()=>supabase.removeChannel(ch)},[])
 async function load(){if(!supabase)return;const {data}=await supabase.from('cafe_posts').select('*').order('created_at',{ascending:false}).limit(50);if(data?.length)setPosts(data.map(p=>({id:p.id,author:p.author_name||'Supporter',room:p.room||'Discussion libre',body:p.body||p.content||'',likes:p.likes_count||0}))) }
 async function publish(){if(!text.trim())return say('Écris un message avant de publier.');if(!supabase){setPosts([{id:Date.now(),author:'Mon compte',room:room.replace(/^.. /,''),body:text,likes:0},...posts]);setText('');return say('Publication ajoutée.')}const {data:{user}}=await supabase.auth.getUser();if(!user){setAuth('login');return say('Connecte-toi pour publier.')}const payload={user_id:user.id,body:text.trim(),room:room.replace(/^.. /,''),author_name:user.user_metadata?.pseudo||user.email?.split('@')[0]};const {error}=await supabase.from('cafe_posts').insert(payload);if(error)return say('Impossible de publier pour le moment.');setText('');say('Publication publiée au Café des Lions.');load()}
 async function submitAuth(){if(!supabase)return say('La connexion Supabase sera active sur le déploiement AtlasFoot.');if(password.length<6||!email)return say('E-mail requis et mot de passe de 6 caractères minimum.');if(signup){const {error}=await supabase.auth.signUp({email,password,options:{data:{pseudo},emailRedirectTo:typeof window!=='undefined'?window.location.origin+'/cafe':undefined}});if(error)return say(error.message);setAuth(null);say('✅ Compte créé avec succès. Vérifiez votre e-mail pour activer votre compte.')}else{const {error}=await supabase.auth.signInWithPassword({email,password});if(error)return say('E-mail ou mot de passe incorrect, ou compte non validé.');setAuth(null);say('Bienvenue dans le Café des Lions !')}}
 return <><header className="top"><div className="wrap nav"><Link className="brand" href="/">ATLAS<b>FOOT</b></Link><nav className="navlinks"><Link href="/">Actualités</Link><Link href="/#xi">Mon XI</Link><Link className="active" href="/cafe">☕ Café des Lions</Link></nav><button className="btn dark" onClick={()=>{setSignup(false);setAuth('login')}}>Se connecter</button><button className="btn red" onClick={()=>{setSignup(true);setAuth('signup')}}>S’inscrire</button></div></header>
 <section className="hero" style={{paddingBottom:28}}><div className="wrap"><span className="eyebrow">☕ 100% SUPPORTERS</span><h1 style={{fontSize:'clamp(38px,5vw,62px)'}}>LE CAFÉ <em>DES LIONS</em></h1><p>Débats, sondages, mercato et passion du football marocain. Ici, la parole est aux supporters.</p></div></section>
 <div className="wrap layout"><aside className="card side"><h4>Salons</h4>{rooms.map(r=><button key={r} className={'room '+(room===r?'active':'')} onClick={()=>setRoom(r)}>{r}</button>)}</aside>
 <main><div className="card compose"><textarea value={text} onChange={e=>setText(e.target.value)} placeholder="Quoi de neuf chez les Lions ?"/><div className="composeFoot"><select className="select" value={room} onChange={e=>setRoom(e.target.value)}>{rooms.slice(1).map(r=><option key={r}>{r}</option>)}</select><button className="btn red" onClick={publish}>Publier</button></div></div>{posts.map(p=><article className="card post" key={p.id}><div className="postHead"><div className="avatar">{p.author?.[0]?.toUpperCase()||'L'}</div><div><b>{p.author}</b><div className="meta">Supporter AtlasFoot</div></div><span className="tag">{p.room}</span></div><p className="postText">{p.body}</p><div className="actions"><button>🤍 {p.likes||0}</button><button>💬 Commenter</button><button>🚩 Signaler</button></div></article>)}</main>
 <aside className="right"><div className="card"><span className="eyebrow">DÉBAT DU JOUR</span><h3>Quel joueur doit être incontournable ?</h3><button className="poll">⚡ Achraf Hakimi</button><button className="poll">🎯 Brahim Díaz</button><button className="poll">🧤 Yassine Bounou</button></div><div className="card"><h3>🔥 Tendances</h3><p>#LionsDeLAtlas</p><p>#MercatoMaroc</p><p>#BotolaPro</p></div><div className="card"><h3>🏅 Supporters</h3><p>Les membres les plus actifs gagneront des badges communautaires.</p></div></aside></div>
 {auth&&<div className="modal"><div className="modalBox"><h2>{signup?'Créer mon compte':'Connexion'}</h2>{signup&&<input value={pseudo} onChange={e=>setPseudo(e.target.value)} placeholder="Pseudo"/>}<input value={email} onChange={e=>setEmail(e.target.value)} type="email" placeholder="E-mail"/><input value={password} onChange={e=>setPassword(e.target.value)} type="password" placeholder="Mot de passe (6 caractères minimum)"/><button className="btn red" style={{width:'100%',marginTop:8}} onClick={submitAuth}>{signup?'Créer mon compte':'Se connecter'}</button><button className="btn dark" style={{width:'100%',marginTop:8}} onClick={()=>setAuth(null)}>Fermer</button></div></div>}{toast&&<div className="toast">{toast}</div>}
 </>}
