const CHANNELS=[{name:'FRMF',id:'UCbQlejA3nCVMq-9qw-oZEtQ'}]
const FRMF_VIDEOS='https://frmf.ma/fr/categorie/videos'
const decode=s=>(s||'').replace(/<!\[CDATA\[|\]\]>/g,'').replace(/&amp;/g,'&').replace(/&#39;|&#039;/g,"'").replace(/&quot;/g,'"').replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/\s+/g,' ').trim()
const tag=(block,name)=>decode((block.match(new RegExp(`<${name}[^>]*>([\\s\\S]*?)<\\/${name}>`,'i'))||[])[1]||'')
const attr=(block,name,attrName)=>((block.match(new RegExp(`<${name}[^>]*${attrName}=["']([^"']+)["'][^>]*>`,'i'))||[])[1]||'')
const strip=s=>decode((s||'').replace(/<[^>]+>/g,' '))
function validVideoId(id){return /^[A-Za-z0-9_-]{11}$/.test(id||'')}
function youtubeId(url=''){const m=String(url).match(/(?:youtube\.com\/(?:watch\?[^#]*v=|embed\/|shorts\/)|youtu\.be\/)([A-Za-z0-9_-]{11})/i);return m?.[1]||''}
function normalizeVideo({id,title,publishedAt,channel='FRMF',thumbnail}){if(!validVideoId(id)||!title||!publishedAt||isNaN(new Date(publishedAt)))return null;return{id,title:decode(title),channel:decode(channel)||'FRMF',publishedAt:new Date(publishedAt).toISOString(),thumbnail:thumbnail||`https://i.ytimg.com/vi/${id}/hqdefault.jpg`,url:`https://www.youtube.com/watch?v=${id}`}}
function parseYouTubeFeed(xml,channel){const entries=xml.match(/<entry>[\s\S]*?<\/entry>/gi)||[];return entries.map(entry=>normalizeVideo({id:tag(entry,'yt:videoId'),title:tag(entry,'title'),publishedAt:tag(entry,'published'),channel:tag(entry,'name')||channel.name,thumbnail:attr(entry,'media:thumbnail','url')})).filter(Boolean)}
function articleLinks(html){const out=[];for(const m of html.matchAll(/href=["'](https?:\/\/frmf\.ma\/fr\/articles\/[^"'#?]+|\/fr\/articles\/[^"'#?]+)["']/gi)){const u=m[1].startsWith('http')?m[1]:'https://frmf.ma'+m[1];if(!out.includes(u))out.push(u)}return out.slice(0,24)}
function pageDate(html){const iso=(html.match(/(?:datePublished|article:published_time)[^>]*content=["']([^"']+)["']/i)||[])[1];if(iso&&!isNaN(new Date(iso)))return new Date(iso).toISOString();const fr=(strip(html).match(/\b(\d{1,2})\s+(janvier|février|mars|avril|mai|juin|juillet|août|septembre|octobre|novembre|décembre)\s+(20\d{2})\b/i)||[]);if(fr.length){const months={janvier:0,'février':1,mars:2,avril:3,mai:4,juin:5,juillet:6,'août':7,septembre:8,octobre:9,novembre:10,'décembre':11};return new Date(Date.UTC(+fr[3],months[fr[2].toLowerCase()],+fr[1],12)).toISOString()}return ''}
function pageTitle(html){return decode((html.match(/<h1[^>]*>([\s\S]*?)<\/h1>/i)||[])[1]?.replace(/<[^>]+>/g,' ')||(html.match(/<meta[^>]+property=["']og:title["'][^>]+content=["']([^"']+)["']/i)||[])[1]||'')}
function pageYouTubeId(html){const urls=[];for(const m of html.matchAll(/(?:src|href)=["']([^"']+(?:youtube\.com|youtu\.be)[^"']*)["']/gi))urls.push(m[1]);for(const u of urls){const id=youtubeId(decode(u));if(validVideoId(id))return id}const raw=html.match(/(?:youtube\.com\/(?:watch\?[^"'<>\s]*v=|embed\/)|youtu\.be\/)([A-Za-z0-9_-]{11})/i);return raw?.[1]||''}
async function fetchText(url){const r=await fetch(url,{redirect:'follow',headers:{'user-agent':'Mozilla/5.0 (compatible; AtlasFoot/1.0; +https://www.atlasfoot.fr)','accept':'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8','accept-language':'fr-FR,fr;q=0.9,en;q=0.7'},cache:'no-store'});if(!r.ok)throw new Error(`${url} ${r.status}`);return r.text()}
async function fromYouTubeRSS(){const results=await Promise.all(CHANNELS.map(async ch=>parseYouTubeFeed(await fetchText(`https://www.youtube.com/feeds/videos.xml?channel_id=${ch.id}`),ch)));return results.flat()}
async function fromRSS2JSON(){const rows=await Promise.all(CHANNELS.map(async ch=>{const feed=`https://www.youtube.com/feeds/videos.xml?channel_id=${ch.id}`;const r=await fetch(`https://api.rss2json.com/v1/api.json?rss_url=${encodeURIComponent(feed)}`,{headers:{'user-agent':'AtlasFoot/1.0','accept':'application/json'},cache:'no-store'});if(!r.ok)throw new Error(`rss2json ${r.status}`);const data=await r.json();if(data.status!=='ok'||!Array.isArray(data.items))throw new Error('rss2json invalid payload');return data.items.map(item=>normalizeVideo({id:youtubeId(item.link)||String(item.guid||'').replace(/^yt:video:/,''),title:item.title,publishedAt:item.pubDate,channel:data.feed?.title||ch.name,thumbnail:item.thumbnail||item.enclosure?.link||''})).filter(Boolean)}));return rows.flat()}
async function fromPublicRelay(){for(const ch of CHANNELS){const feed=`https://www.youtube.com/feeds/videos.xml?channel_id=${ch.id}`;const relays=[`https://api.allorigins.win/raw?url=${encodeURIComponent(feed)}`,`https://corsproxy.io/?url=${encodeURIComponent(feed)}`];for(const url of relays){try{const xml=await fetchText(url);const items=parseYouTubeFeed(xml,ch);if(items.length)return items}catch{}}}return[]}
async function fromOfficialFRMF(){const index=await fetchText(FRMF_VIDEOS);const links=articleLinks(index);const rows=await Promise.allSettled(links.map(async url=>{const html=await fetchText(url);return normalizeVideo({id:pageYouTubeId(html),title:pageTitle(html),publishedAt:pageDate(html),channel:'FRMF'})}));return rows.flatMap(r=>r.status==='fulfilled'&&r.value?[r.value]:[])}
export async function GET(){let items=[];const errors=[];try{items=await fromYouTubeRSS()}catch{errors.push('youtube-rss')}if(!items.length){try{items=await fromRSS2JSON()}catch{errors.push('rss2json')}}if(!items.length){try{items=await fromPublicRelay()}catch{errors.push('public-relay')}}if(!items.length){try{items=await fromOfficialFRMF()}catch{errors.push('frmf-videotheque')}}const seen=new Set();items=items.filter(v=>v&&validVideoId(v.id)&&/^https:\/\/www\.youtube\.com\/watch\?v=[A-Za-z0-9_-]{11}$/.test(v.url)&&!seen.has(v.id)&&(seen.add(v.id),true)).sort((a,b)=>new Date(b.publishedAt)-new Date(a.publishedAt)).slice(0,20);return Response.json({updatedAt:new Date().toISOString(),items,...(!items.length?{error:'Flux vidéo temporairement indisponible',sourcesTried:errors}: {})},{headers:{'Cache-Control':'public, s-maxage=900, stale-while-revalidate=1800'}})}
