import cached from '../../../data/frmf-videos.json'

const CHANNEL={name:'FRMF',id:'UCbQlejA3nCVMq-9qw-oZEtQ'}
const RSSHUBS=['https://rsshub.isrss.com','https://rsshub.pseudoyu.com','https://rsshub.mt.cd','https://rsshub.cups.moe']
const decode=s=>(s||'').replace(/<!\[CDATA\[|\]\]>/g,'').replace(/&amp;/g,'&').replace(/&#39;|&#039;/g,"'").replace(/&quot;/g,'"').replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/\s+/g,' ').trim()
const tag=(block,name)=>decode((block.match(new RegExp(`<${name}[^>]*>([\\s\\S]*?)<\\/${name}>`,'i'))||[])[1]||'')
const attr=(block,name,attrName)=>((block.match(new RegExp(`<${name}[^>]*${attrName}=["']([^"']+)["'][^>]*>`,'i'))||[])[1]||'')
function validVideoId(id){return /^[A-Za-z0-9_-]{11}$/.test(id||'')}
function youtubeId(url=''){const m=String(url).match(/(?:youtube\.com\/(?:watch\?[^#]*v=|embed\/|shorts\/)|youtu\.be\/)([A-Za-z0-9_-]{11})/i);return m?.[1]||''}
function normalizeVideo({id,title,publishedAt,channel='FRMF',thumbnail}){if(!validVideoId(id)||!title||!publishedAt||isNaN(new Date(publishedAt)))return null;return{id,title:decode(title),channel:decode(channel)||'FRMF',publishedAt:new Date(publishedAt).toISOString(),thumbnail:thumbnail||`https://i.ytimg.com/vi/${id}/hqdefault.jpg`,url:`https://www.youtube.com/watch?v=${id}`}}
function parseAtom(xml){const entries=xml.match(/<entry>[\s\S]*?<\/entry>/gi)||[];return entries.map(entry=>normalizeVideo({id:tag(entry,'yt:videoId')||youtubeId(tag(entry,'link')),title:tag(entry,'title'),publishedAt:tag(entry,'published')||tag(entry,'updated'),channel:tag(entry,'name')||CHANNEL.name,thumbnail:attr(entry,'media:thumbnail','url')})).filter(Boolean)}
function parseRss(xml){const items=xml.match(/<item>[\s\S]*?<\/item>/gi)||[];return items.map(item=>{const link=tag(item,'link')||tag(item,'guid');return normalizeVideo({id:youtubeId(link),title:tag(item,'title'),publishedAt:tag(item,'pubDate')||tag(item,'dc:date'),channel:CHANNEL.name,thumbnail:attr(item,'media:thumbnail','url')})}).filter(Boolean)}
async function fetchText(url){const r=await fetch(url,{redirect:'follow',headers:{'user-agent':'Mozilla/5.0 (compatible; AtlasFoot/1.0; +https://www.atlasfoot.fr)','accept':'application/rss+xml,application/atom+xml,application/xml,text/xml;q=0.9,*/*;q=0.6'},cache:'no-store'});if(!r.ok)throw new Error(`${url} ${r.status}`);return r.text()}
async function fromOfficialYouTube(){return parseAtom(await fetchText(`https://www.youtube.com/feeds/videos.xml?channel_id=${CHANNEL.id}`))}
async function fromRssHub(){for(const base of RSSHUBS){try{const xml=await fetchText(`${base}/youtube/channel/${CHANNEL.id}`);const items=[...parseAtom(xml),...parseRss(xml)];if(items.length)return items}catch{}}return[]}
function fromCache(){return Array.isArray(cached?.items)?cached.items.map(normalizeVideo).filter(Boolean):[]}
export async function GET(){let items=[];const sourcesTried=[];try{items=await fromOfficialYouTube()}catch{sourcesTried.push('youtube-rss')}if(!items.length){try{items=await fromRssHub()}catch{sourcesTried.push('rsshub')}}if(!items.length){items=fromCache();if(!items.length)sourcesTried.push('github-cache')}const seen=new Set();items=items.filter(v=>v&&validVideoId(v.id)&&/^https:\/\/www\.youtube\.com\/watch\?v=[A-Za-z0-9_-]{11}$/.test(v.url)&&!seen.has(v.id)&&(seen.add(v.id),true)).sort((a,b)=>new Date(b.publishedAt)-new Date(a.publishedAt)).slice(0,20);return Response.json({updatedAt:new Date().toISOString(),items,...(!items.length?{error:'Flux vidéo temporairement indisponible',sourcesTried}: {})},{headers:{'Cache-Control':'public, s-maxage=900, stale-while-revalidate=1800'}})}
